gateway:
  port: 8192
  address: 0.0.0.0
  pool:
    timeout: 3000 #超时时间
    max-connections: 80 #最大连接数
    max-pending-acquires: 0x7fffffff #最大pending数
  registry:
    nacos:
      server-addr: 192.168.10.224:8848
      namespace: 5dd476b5-316b-4f2e-bf78-06eed9f57ec2
      service-name: AsGateway
#      network-interface: eth0
      network-interface: wlan3
logging:
  level:
    root: info