gateway:
  port: 8192
  address: 0.0.0.0
  pool:
    timeout: 3000 #超时时间
    max-connections: 80 #最大连接数
    max-pending-acquires: 0x7fffffff #最大pending数
  registry:
    nacos:
      server-addr: 172.27.217.61:8848
      namespace: 80a6dec8-f6fd-4dff-beb8-569554671f45
      ip: 172.27.217.61
      service-name: AsGateway
      network-interface: eth0
logging:
  level:
    root: info