gateway:
  port: 8192
  address: 0.0.0.0
  storage-dir: ./
  pool:
    timeout: 3000 #超时时间
    max-connections: 80 #最大连接数
    max-pending-acquires: 0x7fffffff #最大pending数
  registry:
    naming: nacos
    server-addr: 192.168.0.56:8848
    namespace: 06b72914-e3e0-452c-bac6-9b22af6213cd
    service-name: AsGateway
    network-interface: eth0
  redis:
    uri: redis://XCwjj%40xcewell123@192.168.0.176:6379/2?timeout=10s
  endpoint:
    port: 9876
    address: 0.0.0.0
logging:
  level:
    root: info