gateway:
  port: 1723
  address: 0.0.0.0
  storage-dir: ./data
  log-file-size: 20480
  pool:
    timeout: 3000 #超时时间
    max-connections: 80 #最大连接数
    max-pending-acquires: 0x7fffffff #最大pending数
  registry:
    naming: nacos
    server-addr: 123.60.29.248:8848
    namespace: 06b72914-e3e0-452c-bac6-9b22af6213cd
    service-name: AsGateway
    network-interface: en0
  redis:
    uri: redis://XCwjj%40xcewell123@124.71.195.67:6379/2?timeout=10s
  endpoint:
    port: 9876
    address: 0.0.0.0
logging:
  config: classpath:logback-spring.xml
app:
  id: gateway