/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_arise_linux_NativeSupport */

#ifndef _Included_com_arise_linux_NativeSupport
#define _Included_com_arise_linux_NativeSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_arise_linux_NativeSupport
 * Method:    epollWait0
 * Signature: (IJIIII)I
 */
JNIEXPORT jint JNICALL Java_com_arise_linux_NativeSupport_epollWait0
  (JNIEnv *, jclass, jint, jlong, jint, jint, jint, jint);

/*
 * Class:     com_arise_linux_NativeSupport
 * Method:    epollCtlAdd0
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_arise_linux_NativeSupport_epollCtlAdd0
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_arise_linux_NativeSupport
 * Method:    epollCtlModify0
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_arise_linux_NativeSupport_epollCtlModify0
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_arise_linux_NativeSupport
 * Method:    epollCtlDel0
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_arise_linux_NativeSupport_epollCtlDel0
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_arise_linux_NativeSupport
 * Method:    sizeofEpollEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_arise_linux_NativeSupport_sizeofEpollEvent
  (JNIEnv *, jclass);

/*
 * Class:     com_arise_linux_NativeSupport
 * Method:    epollCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_arise_linux_NativeSupport_epollCreate
  (JNIEnv *, jclass);

/*
 * Class:     com_arise_linux_NativeSupport
 * Method:    eventFd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_arise_linux_NativeSupport_eventFd
  (JNIEnv *, jclass);

/*
 * Class:     com_arise_linux_NativeSupport
 * Method:    timerFd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_arise_linux_NativeSupport_timerFd
  (JNIEnv *, jclass);

/*
 * Class:     com_arise_linux_NativeSupport
 * Method:    write2EventFd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_arise_linux_NativeSupport_write2EventFd
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_arise_linux_NativeSupport
 * Method:    offsetofEpollData
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_arise_linux_NativeSupport_offsetofEpollData
  (JNIEnv *, jclass);

/*
 * Class:     com_arise_linux_NativeSupport
 * Method:    taskset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_arise_linux_NativeSupport_taskset
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
